export default ["!Xóõ",
  "Aasá",
  "Aбаза бызшва",
  "Ayta Abellen ",
  "Alnôba",
  "Aҧсуа бызшәа",
  "Abui",
  "Abure",
  "Achang",
  "Achi",
  "Achinese",
  "Achumawi",
  "Achomawi or Ajúmmááwí",
  "Adai",
  "Adangbɛ",
  "Adangbe",
  "Gidire",
  "Adioukrou",
  "Adnyamathanha",
  "Адыгабзэ",
  "Afade",
  "Qafár af",
  "El-Afrihili",
  "Afrikaans",
  "Aguacateco",
  "Aghem",
  "Aghul",
  "Ahtena",
  "アイヌ イタク",
  "A’jie",
  "Akan",
  "Akkadian",
  "Akkala Sámi",
  "Aklanon",
  "Akum",
  "Alabama",
  "Shqip",
  "Alergian Saharan Arabic",
  "Unangam Tunuu",
  "Algonquin",
  "Altai",
  "Altai",
  "Sìmí Amdangtí",
  "ኣማርኛ",
  "Amo",
  "𓂋𓏤𓈖𓆎𓅓𓏏𓊖 ",
  "Ἑλληνική",
  "Ἑλληνική",
  "عربية أندلسية",
  "Anfillo",
  "अंगिका",
  "Angloromani",
  "Ndéé",
  "Apsaalooke",
  "Arabela",
  "العربية",
  "l'Aragonés",
  "ܐܪܡܝܐ",
  "Hinono'eitiitt",
  "Arbëreshë Albanian",
  "Archi",
  "Arikara",
  "Arin",
  "bbˈirk",
  "Հայերեն",
  "Arpitan",
  "Arrernte Angkentye",
  "arbërisht or αρbε̰ρίσ̈τ",
  "অসমীয়া",
  "Assiniboine",
  "Asturianu",
  "Sign Language",
  "Atikamekw",
  "МагIарул МацI",
  "𐬆𐬬𐬈𐬯𐬙𐬆𐬥",
  "Awadhi",
  "Aweer",
  "Awijilah",
  "Ayapaneco\n",
  "Aymar Aru",
  "ئەينۇ",
  "Azərbaycanca",
  "Azoyu Me'phaa",
  "Babine",
  "Barka",
  "白语",
  "Baki",
  "ᬩᬲᬩᬮᬶ",
  "སྦལ་ཏིའི་སྐད་",
  "Bamanankan",
  "Narrow Bantu",
  "Basa-Kaduna",
  "башҡорт Теле",
  "Euskara",
  "ɓasaá",
 
  "Беларуская",
  "iciBemba",
  "বাংলা",
  "Tamaziɣt",
  "Gebeto or Wetawit",
  "भोजपुरी",
  "Bijago",
  "Bislama",
  "ᑯᖾᖹ",
  "बड़ो",
  "Босански",
  "Brezhoneg",
  "ᨅᨔ ᨕᨘᨁᨗ",
  "ᝊᝓᝑᝒᝇ",
  "български език",
  "မြန်မာစာ or မြန်မာစကား",
  "Mossittaata",
  "Caddo",
  "Ivia",
  "Canichana",
  "Canichana † -\xa0?\n",
  "廣東話",
  "ᑐᑊᘁᗕᑋᗸ",
  "Català",
  "Catawba",
  "Iyeye",
  "Gayogo̱hó:nǫ’",
  "Bisaya",
  "Chalcatongo Mixtec\n",
  "Cham",
  "Chamoru",
  "Нохчийн Mотт",
  "ᏣᎳᎩ",
  "Nyanja",
  "Tsėhesenėstsestotse",
  "छत्तीसगढ़ी",
  "Chikasha",
  "汉语",
  "ᑌᓀᓲᒢᕄᓀ",
  "Chittagonian",
  "Chocangaca",
  "Chahta",
  "Chukchi",
  "Чӑвашла",
  "Zimbrisch",
  "Cocos Islands Malay",
  "Nʉmʉ Tekwapʉ",
  "‘Airani",
  "ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ",
  "Kernewek",
  "Corsu",
  "ᓀᐦᐃᔭᐍᐏᐣ",
  "Crimean Tatar",
  "Hrvatski",
  "Kupangaxwicham Pe'memelki",
  "Sanna",
  "Český Jazyk",
  "Dair",
  "دکنی",
  "Dakȟótiyapi",
  "Dalmål",
  "Dansk",
  "Дарган Mез",
  "فارسی",
  "ދިވެހި",
  "Dômarî",
  "Dehu",
  "回族语言",
  "Durkha",
  "Nederlands",
  "rapmotz",
  "རྫོང་ཁ་",
  "E",
  "اللغة المصرية العامية",
  "English",
  "Эрзянь Kель",
  "Esperantaj",
  "Eesti",
  "Even",
  "Эвэды̄ турэ̄н",
  "Èʋe",
  "Extremaduran",
  "I•ya•q",
  "I•ya•q",
  "Fala",
  "Føroyskt",
  "Na vosa vaka-Viti",
  "फिजी बात or Fiji Baat",
  "Wikang Filipino",
  "Suomi",
  "Fon gbè",
  "Français",
  "Noordfreesk",
  "Seeltersk",
  "Frysk",
  "Furlan",
  "Fulfulde",
  "For",
  "Gã",
  "Gagauz",
  "Galego",
  "Gallo",
  "赣语",
  "Garre",
  "ግዕዝ",
  "ქართული",
  "Deutsch",
  "Gĩkũyũ",
  "Taetae ni Kiribati",
  "ГъибдилӀи Mицци",
  "𐌲𐌿𐍄𐌹𐍃𐌺",
  "Ελληνικά",
  "Kalaallisut",
  "Grenadian French Creole",
  "Avañe'ẽ or Javy ju",
  "ગુજરાતી",
  "Bega",
  "तमु क्यी",
  "Gwich'in",
  "Xaat Kíl",
  "海南話",
  "Kreyòl Ayisyen",
  "客家話",
  "ሃራሪ",
  "Haryanvi",
  "حَوْسَ",
  "ʻŌlelo Hawaiʻi",
  "Otjiherero",
  "Omuhimba",
  "हिन्दी",
  "ہندوستانی",
  "Hiri Motu",
  "lol Hmongb",
  "Hopilàvayi or Hopílavayi",
  "Magyar",
  "Íslenska",
  "Ido",
  "Asụsụ Igbo",
  "Icetot",
  "Ili Turki",
  "Iloko",
  "Bahasa Indonesia",
  "ГӀалгӀай мотт",
  "Interlingua",
  "Interlingue",
  "Medžuslovjansky",
  "Inuinnaqtun -\xa0?\n",
  "Atgangmuurngniq",
  "ᐃᓄᒃᑎᑐᑦ",
  "Iñupiatun",
  "Gaeilge",
  "Mela'tájtol",
  "Istro Romanian",
  "Italiano",
  "日本語",
  "Jarawa",
  "ꦧꦱꦗꦮ",
  "גֿודֿיאו-איספאנייול\u200e",
  "Jydsk",
  "Jèrriais",
  "Адыгэбзэ",
  "شئعم",
  "Kanhgág",
  "Kaixana",
  "ಕನ್ನಡ",
  "Kanuri",
  "Қарақалпақ тили",
  "ŋaKaramojoŋ or ŋaKarimojoŋ",
  "Karjalan Kieli",
  "كٲشُر,\tकॉशुर",
  "Kaszëbsczi Jãzëk",
  "Қазақ Tілі",
  "بهاس ملايو كلنتن or Baso Kelate",
  "Kendeje",
  "Остыганна ӄа'",
  "Хакас Tілі",
  "ភាសាខ្មែរ",
  "Khoekhoegowab",
  "کھوار",
  "Kimki",
  "Ikinyarwanda or Runyarwanda",
  "Taetae Ni Kiribati",
  "कोंकणी",
  "조선말",
  "Kosraean",
  "Tinata Tuna",
  "Kunama",
  "Rub",
  "Къумукъ Tил",
  "Kurdí",
  "کوردی خوارین",
  "Kurmancî",
  "کچھی or કચ્છી",
  "!Kwa/tse",
  "Laal",
  "ལ་དྭགས་སྐད།",
  "Ladin",
  "Lakha",
  "Lakȟótiyapi",
  "ພາສາລາວ",
  "Lingua Latīna",
  "latviešu",
  "ლაზური ნენა",
  "Llïonés",
  "ᰛᰩᰵ་ᰛᰧᰶᰵ",
  "ᤕᤰᤌᤢᤱ ᤐᤠᤴ",
  "Lèmburgs",
  "Lingála",
  "ꓡꓲ-ꓢꓴ or ꓡꓲꓢꓴ",
  "Lietuvių",
  "Līvõ Kēļ or Rāndakēļ",
  "Plattdüütsch",
  "Low Prussian Dialect",
  "Tshiluba",
  "Luganda",
  "Cham'teela",
  "Kavirondo or Dholuo",
  "لری or Lori",
  "Lëtzebuergesch",
  "ɔl Maa",
  "Mакедонски",
  "Madurese",
  "मगही",
  "मगर भाषा",
  "मैथिली",
  "Basa Mangkasara",
  "Malagasy",
  "بهاس ملايو or Bahasa Melayu",
  "മലയാളം",
  "Malti",
  "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ",
  "國語",
  "Gaelg",
  "मराठी",
  "Ebon",
  "Marwari",
  "kana masara",
  "মনিপুরি",
  "Myaamia",
  "Pómaro Nahuatl",
  "閩語 or 闽语",
  "闽北语",
  "閩東語",
  "閩南語 or 闽南语",
  "闽中话",
  "ဘာသာ မန်",
  "Монгол Хэл",
  "crnogorski",
  "Mon-Khmer",
  "Mor",
  "Mvskoke",
  "Mulwi",
  "Muzuk",
  "Mussau-Emira",
  "te Reo Māori",
  "Gong or Ngong",
  "Māsēwallahtōlli",
  "Diné bizaad",
 
  "नेपाल भाषा",
  "नेपाली",
  "Sign Language",
  "Lingbee",
  "Nihali",
  "ᨣᩴᩤᨾᩮᩥᩬᨦ",
  "Norsk",
  "ꆈꌠ꒿",
  "Nyang'i",
  "Occitan",
  "ଓଡ଼ିଆ",
  "Oirat",
  "Oirata",
  "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  "ウチナーヤマトゥグチ",
  "Словѣ́ньскъ Ѩзꙑ́къ",
  "Anglisc",
  "Laamoot",
  "Onge",
  "Oromo",
  "Ossetian",
  "पहाड़ी",
  "پالولہ",
  "Paratio",
  "Paratio †  -\n",
  "پښتو",
  "بهاس جاوي",
  "فارسی",
  "𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌",
  "Tepiman",
  "Náhuat or Nawat",
  "Pirahã",
  "Pitjantjatjara",
  "Plautdietsch",
  "Język polski",
  "Português",
  "पंजाबी",
  "興化話 or 莆仙話",
  "Quechuan",
  "Quinqui",
  "Hano",
  "राजस्थानी",
  "Rohingya\n",
  "Romani Ćhib",
  "Română",
  "Ramanos",
  "Ramanos †-\xa0?\n",
  "Rumantsch",
  "Русский",
  "Русиньский Язык",
  "Руский Языкъ",
  "Rotokas",
  "anarâškielâ",
  "Кӣллт са̄мь кӣлл",
  "julevsámegiella",
  "davvisámegiella",
  "bidumsámegiella",
  "sääʹmǩiõll",
  "åarjelsaemien gïele",
  "Са̄мькӣлл",
  "ubmejensámien giella",
  "Gagana Sāmoa",
  "संस्कृतम्",
  "Sardu",
  "ꢱꣃꢬꢵꢰ꣄ꢜ꣄ꢬꢵ",
  "Scots",
  "Gàidhlig",
  "Српски",
  "srpskohrvatski/српскохрватски",
  "Seereer",
  "လိၵ်ႈတႆး",
  "上海闲话",
  "शेर्पा",
  "Shona",
  "Sicilianu",
  "འབྲས་ལྗོངས་",
  "سنڌي",
  "සිංහල",
  "Slovenčina",
  "Slovianski",
  "Slovenščina",
  "اللغة الصومالية",
  "سۆرانی",
  "Sesotho",
  "Southern Quechua\n",
  "Español",
  "Stellingwerfs",
  "ᮘᮞ ᮞᮥᮔ᮪ᮓ",
  "Sumerian",
  "Susuami",
  "Kiswahili",
  "Svenska",
  "Schwyzerdütsch",
  "ছিলটী",
  "ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
  "Reo Mā'ohi",
  "ꪺꪕꪒꪾ",
  "ไทเขิน",
  "ᦑᦺᦟᦹᧉ",
  "ᥖᥭᥰᥖᥬᥳᥑᥨᥒᥰ",
  "तामाङ",
  "தமிழ்",
  "تاتارچا",
  "తెలుగు",
  "Soo",
  "Naso",
  "Lia-Tetun",
  "ภาษาไทย",
  "དབུས་སྐད་",
  "ትግርኛ",
  "Tobagonian Creole -\xa0?\n",
  "Tok Pisin",
  "Lea faka-Tonga",
  "Gabrielino",
  "Trinidadian Creole -\xa0?\n",
  "Цез Мец",
  "Setswana",
  "Tamahaq",
  "Luhchi Yoroni",
  "\tتونسي",
  "Türkçe",
  "Turkmen",
  "Tulu language ತುಳು ಬಾಸೆ",
  "Tumpoon",
  "Tübatulabal",
  "Ubykh",
  "Tw'ampa or T'wampa",
  "Українська",
  "Upper Sorbian",
  "اُردُو",
  "Uspanteco",
  "ئۇيغۇر تىلى",
  "اوزبیک",
  "Vaagri Booli",
  "Vai",
  "Valencià",
  "Vedda",
  "Tshivenḓa",
  "Vèneto",
  "Tiếng Việt Nam",
  "Naygar (meaning people not Vincentian Creole)",
  "Vlax Romani",
  "Volapük",
  "Votic",
  "Võro Kiil",
  "Walloon",
  "Warlpiri",
  "Cymraeg",
  "Western Itelmen",
  "Frysk",
  "Wintu",
  "Wolof",
  "吴方言",
  "Kanala",
  "Xhosa",
  "湘语",
  "ᠰᡞᠪᡝᡤᡞᠰᡠᠨ",
  "Xucuru",
  "Xiriâna † -\xa0?\n",
  "Yapese",
  "Yakut",
  "Yanesha'",
  "Pasco",
  "ייִדיש\tייִדיש\u200e",
  "Èdè Yorùbá",
  "Yuchi",
  "粵語",
  "Zaghawa",
  "Zaza",
  "Zulu",
  "Zuni",
  "話僮"
]